//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 原始文件名:
// 生成日期: 2016/12/27 PM 06:28:25
namespace WTD.Admin.DataService
{
    
    /// <summary>
    /// 架构中不存在 Container 的注释。
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// 初始化新的 Container 对象。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// 因为在 Visual Studio 中为此服务引用配置的
        /// 命名空间与在服务器架构中指示的命名空间不同，所以
        /// 使用类型映射器在这两者之间进行映射。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Skyline.Common.Models", "WTD.Admin.DataService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// 因为在 Visual Studio 中为此服务引用配置的
        /// 命名空间与在服务器架构中指示的命名空间不同，所以
        /// 使用类型映射器在这两者之间进行映射。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("WTD.Admin.DataService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Skyline.Common.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// 架构中不存在 AnimeInfoes 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<AnimeInfo> AnimeInfoes
        {
            get
            {
                if ((this._AnimeInfoes == null))
                {
                    this._AnimeInfoes = base.CreateQuery<AnimeInfo>("AnimeInfoes");
                }
                return this._AnimeInfoes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<AnimeInfo> _AnimeInfoes;
        /// <summary>
        /// 架构中不存在 ShipLogs 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ShipLog> ShipLogs
        {
            get
            {
                if ((this._ShipLogs == null))
                {
                    this._ShipLogs = base.CreateQuery<ShipLog>("ShipLogs");
                }
                return this._ShipLogs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ShipLog> _ShipLogs;
        /// <summary>
        /// 架构中不存在 ItemInfoes 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ItemInfo> ItemInfoes
        {
            get
            {
                if ((this._ItemInfoes == null))
                {
                    this._ItemInfoes = base.CreateQuery<ItemInfo>("ItemInfoes");
                }
                return this._ItemInfoes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ItemInfo> _ItemInfoes;
        /// <summary>
        /// 架构中不存在 ItemNo2Infoes 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ItemNo2Info> ItemNo2Infoes
        {
            get
            {
                if ((this._ItemNo2Infoes == null))
                {
                    this._ItemNo2Infoes = base.CreateQuery<ItemNo2Info>("ItemNo2Infoes");
                }
                return this._ItemNo2Infoes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ItemNo2Info> _ItemNo2Infoes;
        /// <summary>
        /// 架构中不存在 AnimeInfoes 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAnimeInfoes(AnimeInfo animeInfo)
        {
            base.AddObject("AnimeInfoes", animeInfo);
        }
        /// <summary>
        /// 架构中不存在 ShipLogs 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToShipLogs(ShipLog shipLog)
        {
            base.AddObject("ShipLogs", shipLog);
        }
        /// <summary>
        /// 架构中不存在 ItemInfoes 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToItemInfoes(ItemInfo itemInfo)
        {
            base.AddObject("ItemInfoes", itemInfo);
        }
        /// <summary>
        /// 架构中不存在 ItemNo2Infoes 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToItemNo2Infoes(ItemNo2Info itemNo2Info)
        {
            base.AddObject("ItemNo2Infoes", itemNo2Info);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"Skyline.Common.Models\" xmlns=\"http://schemas.microsoft.com/ado/2009/1" +
                "1/edm\"><EntityType Name=\"AnimeInfo\"><Key><PropertyRef Name=\"Id\" /></Key><Propert" +
                "y Name=\"Id\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"Title\" Type=\"Edm." +
                "String\" /><Property Name=\"First\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Propert" +
                "y Name=\"Weekday\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Keyword\" Ty" +
                "pe=\"Edm.String\" /></EntityType><EntityType Name=\"ShipLog\"><Key><PropertyRef Name" +
                "=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property N" +
                "ame=\"Time\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"Area\" Type=\"Ed" +
                "m.String\" /><Property Name=\"Enemy\" Type=\"Edm.String\" /><Property Name=\"Rank\" Typ" +
                "e=\"Edm.String\" /><Property Name=\"Drop\" Type=\"Edm.String\" /><Property Name=\"Fight" +
                "\" Type=\"Edm.Guid\" /></EntityType><EntityType Name=\"ItemInfo\"><Key><PropertyRef N" +
                "ame=\"Name\" /></Key><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" /><P" +
                "roperty Name=\"Type\" Type=\"Edm.String\" /><Property Name=\"Icon\" Type=\"Edm.String\" " +
                "/><NavigationProperty Name=\"ItemNo2Info\" Relationship=\"Skyline.Common.Models.Sky" +
                "line_Common_Models_ItemInfo_ItemNo2Info_Skyline_Common_Models_ItemNo2Info_ItemNo" +
                "2InfoPartner\" ToRole=\"ItemNo2Info\" FromRole=\"ItemNo2InfoPartner\" /></EntityType>" +
                "<EntityType Name=\"ItemNo2Info\"><Key><PropertyRef Name=\"Id\" /></Key><Property Nam" +
                "e=\"Id\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"Item\" Type=\"Edm.String" +
                "\" /><Property Name=\"Name\" Type=\"Edm.String\" /><Property Name=\"Weekdays\" Type=\"Ed" +
                "m.String\" /><Property Name=\"Target\" Type=\"Edm.String\" /><Property Name=\"Cost\" Ty" +
                "pe=\"Edm.String\" /><NavigationProperty Name=\"ItemInfo\" Relationship=\"Skyline.Comm" +
                "on.Models.Skyline_Common_Models_ItemNo2Info_ItemInfo_Skyline_Common_Models_ItemI" +
                "nfo_ItemInfoPartner\" ToRole=\"ItemInfo\" FromRole=\"ItemInfoPartner\" /></EntityType" +
                "><Association Name=\"Skyline_Common_Models_ItemInfo_ItemNo2Info_Skyline_Common_Mo" +
                "dels_ItemNo2Info_ItemNo2InfoPartner\"><End Type=\"Skyline.Common.Models.ItemNo2Inf" +
                "o\" Role=\"ItemNo2Info\" Multiplicity=\"*\" /><End Type=\"Skyline.Common.Models.ItemIn" +
                "fo\" Role=\"ItemNo2InfoPartner\" Multiplicity=\"0..1\" /></Association><Association N" +
                "ame=\"Skyline_Common_Models_ItemNo2Info_ItemInfo_Skyline_Common_Models_ItemInfo_I" +
                "temInfoPartner\"><End Type=\"Skyline.Common.Models.ItemInfo\" Role=\"ItemInfo\" Multi" +
                "plicity=\"0..1\" /><End Type=\"Skyline.Common.Models.ItemNo2Info\" Role=\"ItemInfoPar" +
                "tner\" Multiplicity=\"0..1\" /></Association></Schema><Schema Namespace=\"Default\" x" +
                "mlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"Conta" +
                "iner\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"AnimeInfoes\" EntityType" +
                "=\"Skyline.Common.Models.AnimeInfo\" /><EntitySet Name=\"ShipLogs\" EntityType=\"Skyl" +
                "ine.Common.Models.ShipLog\" /><EntitySet Name=\"ItemInfoes\" EntityType=\"Skyline.Co" +
                "mmon.Models.ItemInfo\" /><EntitySet Name=\"ItemNo2Infoes\" EntityType=\"Skyline.Comm" +
                "on.Models.ItemNo2Info\" /><AssociationSet Name=\"Skyline_Common_Models_ItemInfo_It" +
                "emNo2Info_Skyline_Common_Models_ItemNo2Info_ItemNo2InfoPartnerSet\" Association=\"" +
                "Skyline.Common.Models.Skyline_Common_Models_ItemInfo_ItemNo2Info_Skyline_Common_" +
                "Models_ItemNo2Info_ItemNo2InfoPartner\"><End Role=\"ItemNo2InfoPartner\" EntitySet=" +
                "\"ItemInfoes\" /><End Role=\"ItemNo2Info\" EntitySet=\"ItemNo2Infoes\" /></Association" +
                "Set><AssociationSet Name=\"Skyline_Common_Models_ItemNo2Info_ItemInfo_Skyline_Com" +
                "mon_Models_ItemInfo_ItemInfoPartnerSet\" Association=\"Skyline.Common.Models.Skyli" +
                "ne_Common_Models_ItemNo2Info_ItemInfo_Skyline_Common_Models_ItemInfo_ItemInfoPar" +
                "tner\"><End Role=\"ItemInfoPartner\" EntitySet=\"ItemNo2Infoes\" /><End Role=\"ItemInf" +
                "o\" EntitySet=\"ItemInfoes\" /></AssociationSet></EntityContainer></Schema></edmx:D" +
                "ataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 Skyline.Common.Models.AnimeInfo 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("AnimeInfoes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class AnimeInfo : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 AnimeInfo 对象。
        /// </summary>
        /// <param name="ID">Id 的初始值。</param>
        /// <param name="first">First 的初始值。</param>
        /// <param name="weekday">Weekday 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static AnimeInfo CreateAnimeInfo(global::System.Guid ID, global::System.DateTime first, int weekday)
        {
            AnimeInfo animeInfo = new AnimeInfo();
            animeInfo.Id = ID;
            animeInfo.First = first;
            animeInfo.Weekday = weekday;
            return animeInfo;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 Title 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// 架构中不存在属性 First 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime First
        {
            get
            {
                return this._First;
            }
            set
            {
                this.OnFirstChanging(value);
                this._First = value;
                this.OnFirstChanged();
                this.OnPropertyChanged("First");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _First;
        partial void OnFirstChanging(global::System.DateTime value);
        partial void OnFirstChanged();
        /// <summary>
        /// 架构中不存在属性 Weekday 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Weekday
        {
            get
            {
                return this._Weekday;
            }
            set
            {
                this.OnWeekdayChanging(value);
                this._Weekday = value;
                this.OnWeekdayChanged();
                this.OnPropertyChanged("Weekday");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Weekday;
        partial void OnWeekdayChanging(int value);
        partial void OnWeekdayChanged();
        /// <summary>
        /// 架构中不存在属性 Keyword 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Keyword
        {
            get
            {
                return this._Keyword;
            }
            set
            {
                this.OnKeywordChanging(value);
                this._Keyword = value;
                this.OnKeywordChanged();
                this.OnPropertyChanged("Keyword");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Keyword;
        partial void OnKeywordChanging(string value);
        partial void OnKeywordChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 Skyline.Common.Models.ShipLog 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ShipLogs")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class ShipLog : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 ShipLog 对象。
        /// </summary>
        /// <param name="ID">Id 的初始值。</param>
        /// <param name="time">Time 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ShipLog CreateShipLog(global::System.Guid ID, global::System.DateTime time)
        {
            ShipLog shipLog = new ShipLog();
            shipLog.Id = ID;
            shipLog.Time = time;
            return shipLog;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 Time 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Time
        {
            get
            {
                return this._Time;
            }
            set
            {
                this.OnTimeChanging(value);
                this._Time = value;
                this.OnTimeChanged();
                this.OnPropertyChanged("Time");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Time;
        partial void OnTimeChanging(global::System.DateTime value);
        partial void OnTimeChanged();
        /// <summary>
        /// 架构中不存在属性 Area 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Area
        {
            get
            {
                return this._Area;
            }
            set
            {
                this.OnAreaChanging(value);
                this._Area = value;
                this.OnAreaChanged();
                this.OnPropertyChanged("Area");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Area;
        partial void OnAreaChanging(string value);
        partial void OnAreaChanged();
        /// <summary>
        /// 架构中不存在属性 Enemy 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Enemy
        {
            get
            {
                return this._Enemy;
            }
            set
            {
                this.OnEnemyChanging(value);
                this._Enemy = value;
                this.OnEnemyChanged();
                this.OnPropertyChanged("Enemy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Enemy;
        partial void OnEnemyChanging(string value);
        partial void OnEnemyChanged();
        /// <summary>
        /// 架构中不存在属性 Rank 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Rank
        {
            get
            {
                return this._Rank;
            }
            set
            {
                this.OnRankChanging(value);
                this._Rank = value;
                this.OnRankChanged();
                this.OnPropertyChanged("Rank");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Rank;
        partial void OnRankChanging(string value);
        partial void OnRankChanged();
        /// <summary>
        /// 架构中不存在属性 Drop 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Drop
        {
            get
            {
                return this._Drop;
            }
            set
            {
                this.OnDropChanging(value);
                this._Drop = value;
                this.OnDropChanged();
                this.OnPropertyChanged("Drop");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Drop;
        partial void OnDropChanging(string value);
        partial void OnDropChanged();
        /// <summary>
        /// 架构中不存在属性 Fight 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> Fight
        {
            get
            {
                return this._Fight;
            }
            set
            {
                this.OnFightChanging(value);
                this._Fight = value;
                this.OnFightChanged();
                this.OnPropertyChanged("Fight");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _Fight;
        partial void OnFightChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnFightChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 Skyline.Common.Models.ItemInfo 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Name
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ItemInfoes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Name")]
    public partial class ItemInfo : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 ItemInfo 对象。
        /// </summary>
        /// <param name="name">Name 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ItemInfo CreateItemInfo(string name)
        {
            ItemInfo itemInfo = new ItemInfo();
            itemInfo.Name = name;
            return itemInfo;
        }
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 Type 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// 架构中不存在属性 Icon 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Icon
        {
            get
            {
                return this._Icon;
            }
            set
            {
                this.OnIconChanging(value);
                this._Icon = value;
                this.OnIconChanged();
                this.OnPropertyChanged("Icon");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Icon;
        partial void OnIconChanging(string value);
        partial void OnIconChanged();
        /// <summary>
        /// 架构中不存在 ItemNo2Info 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ItemNo2Info> ItemNo2Info
        {
            get
            {
                return this._ItemNo2Info;
            }
            set
            {
                this._ItemNo2Info = value;
                this.OnPropertyChanged("ItemNo2Info");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ItemNo2Info> _ItemNo2Info = new global::System.Data.Services.Client.DataServiceCollection<ItemNo2Info>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 Skyline.Common.Models.ItemNo2Info 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ItemNo2Infoes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class ItemNo2Info : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 ItemNo2Info 对象。
        /// </summary>
        /// <param name="ID">Id 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ItemNo2Info CreateItemNo2Info(global::System.Guid ID)
        {
            ItemNo2Info itemNo2Info = new ItemNo2Info();
            itemNo2Info.Id = ID;
            return itemNo2Info;
        }
        /// <summary>
        /// 架构中不存在属性 Id 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// 架构中不存在属性 Item 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Item
        {
            get
            {
                return this._Item;
            }
            set
            {
                this.OnItemChanging(value);
                this._Item = value;
                this.OnItemChanged();
                this.OnPropertyChanged("Item");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Item;
        partial void OnItemChanging(string value);
        partial void OnItemChanged();
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 Weekdays 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Weekdays
        {
            get
            {
                return this._Weekdays;
            }
            set
            {
                this.OnWeekdaysChanging(value);
                this._Weekdays = value;
                this.OnWeekdaysChanged();
                this.OnPropertyChanged("Weekdays");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Weekdays;
        partial void OnWeekdaysChanging(string value);
        partial void OnWeekdaysChanged();
        /// <summary>
        /// 架构中不存在属性 Target 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Target
        {
            get
            {
                return this._Target;
            }
            set
            {
                this.OnTargetChanging(value);
                this._Target = value;
                this.OnTargetChanged();
                this.OnPropertyChanged("Target");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Target;
        partial void OnTargetChanging(string value);
        partial void OnTargetChanged();
        /// <summary>
        /// 架构中不存在属性 Cost 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Cost
        {
            get
            {
                return this._Cost;
            }
            set
            {
                this.OnCostChanging(value);
                this._Cost = value;
                this.OnCostChanged();
                this.OnPropertyChanged("Cost");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Cost;
        partial void OnCostChanging(string value);
        partial void OnCostChanged();
        /// <summary>
        /// 架构中不存在 ItemInfo 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ItemInfo ItemInfo
        {
            get
            {
                return this._ItemInfo;
            }
            set
            {
                this._ItemInfo = value;
                this.OnPropertyChanged("ItemInfo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ItemInfo _ItemInfo;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
